<?php

/**
 * @file
 * Contains emmr_core.module.
 */

use Drupal\block\Entity\Block;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_hook().
 */
function emmr_core_preprocess_emmr_intro(&$variables) {
  $block = Block::load('exposedformbrowse_recipes_v2page_2');
  $variables['search_block_output'] = \Drupal::entityTypeManager()
    ->getViewBuilder('block')
    ->view($block);
}

/**
 * Implements hook_theme().
 */
function emmr_core_theme($existing, $type, $theme, $path) {
  return [
    'emmr_intro' => [
      'variables' => [],
    ],
    'node__emmr_recipe__full' => [
      'arguments' => [
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ],
      'template' => 'node--emmr-recipe--full',
      'path' => \Drupal::service('extension.list.module')->getPath('emmr_core') . '/templates',
      'base hook' => 'node__emmr_recipe__full',
    ],
    'node__emmr_recipe__pdf' => [
      'arguments' => [
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ],
      'template' => 'node--emmr-recipe--pdf',
      'path' => \Drupal::service('extension.list.module')->getPath('emmr_core') . '/templates',
      'base hook' => 'node__emmr_recipe__pdf',
    ],
    'node__emmr_source__full' => [
      'arguments' => [
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ],
      'template' => 'node--emmr-source--full',
      'path' => \Drupal::service('extension.list.module')->getPath('emmr_core') . '/templates',
      'base hook' => 'node__emmr_source__full',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function emmr_core_preprocess_node(&$variables) {
  $node = $variables['node'];

  if ($node->bundle() == 'emmr_source') {
    drupal_flush_all_caches();
  }

  if ($node->bundle() == 'emmr_recipe') {
    // Process annotations.
    // Recover transcription.
    $trans = !empty($node->get('field_recipe_transcription')->getValue()[0]) ?
      $node->get('field_recipe_transcription')->getValue()[0]['value'] : "";

    // Update annotations.
    $annos = !empty($node->get('field_annotations')->getValue()) ?
      $node->get('field_annotations')->getValue() : [];

    if ($annos) {
      $annos_num = count($variables['content']['field_annotations']['#items']);
      $annos_val = [];
      $annos_alt = [];
      $i = 0;

      while ($i < $annos_num) {

        if (!empty($variables['content']['field_annotations'][$i]['#paragraph']->get('field_annotation_text')->getValue()[0]['value'])) {
          $anno =
            trim($variables['content']['field_annotations'][$i]['#paragraph']->get('field_annotation_text')->getValue()[0]['value']);

          $annos_val[] = $anno;
        }

        // Include alternative spellings.
        $alt_spellings = $variables['content']['field_annotations'][$i]['#paragraph']->get('field_alt_spellings')->getValue();

        foreach ($alt_spellings as $spelling) {

          if (trim($spelling['value']) != $anno) {
            $annos_alt[] = [$annos_val[$i], trim($spelling['value'])];
          }
        }

        $i++;
      }

      // Highlight annotation text.
      foreach ($annos_val as $val) {
        $val = preg_replace('/(^[[:punct:]]|[[:punct:]]$)/', '', $val);
        $pattern = '/(\b\Q' . $val . '\E\b)/mi';
        $anno_id = 'top-' . $val;

        $replacement = '<span id="' . $anno_id .
          '" class="emmr-anno"><a href="#anno-' . $val . '">$1</a></span>';

        $trans = preg_replace($pattern, $replacement, $trans);
      }

      // Highlight alternative spellings.
      foreach ($annos_alt as $val) {
        $pattern = '/(\b\Q' . $val[1] . '\E\b)/mi';
        $anno_id = 'top-' . $val[0];

        $replacement = '<span id="' . $anno_id .
          '" class="emmr-anno"><a href="#anno-' . $val[0] . '">$1</a></span>';

        $trans = preg_replace($pattern, $replacement, $trans);
      }

      $variables['content']['field_recipe_transcription'][0]['#text'] = $trans;
    }

    // Add source data.
    if (!empty($node->get('field_recipe_source')->getValue()[0]['target_id'])) {
      $sid = intval($node->get('field_recipe_source')->getValue()[0]['target_id']);

      if (!empty(Node::load($sid))) {
        $source = Node::load($sid);

        $sname = $source->getTitle();

        $iid = !empty($source->get('field_institution')->getValue()[0]['target_id']) ?
          $source->get('field_institution')->getValue()[0]['target_id'] : NULL;
        $institution = !empty($iid) ? Term::load($iid)->getName() : "";

        $origin = !empty($source->get('field_source_origin')->getValue()[0]) ?
          $source->get('field_source_origin')->getValue()[0]['value'] : "";
        $sublocation = !empty($source->get('field_sublocation')->getValue()) ?
          $source->get('field_sublocation')->getValue()[0]['value'] : "";
        $reference = !empty($source->get('field_reference')->getValue()) ?
          $source->get('field_reference')->getValue()[0]['value'] : "";

        $variables['source']['url'] = $source->toUrl()->toString();
        $variables['source']['name'] = $sname;
        $variables['source']['institution'] = $institution;
        $variables['source']['origin'] = $origin;
        $variables['source']['sublocation'] = $sublocation;
        $variables['source']['reference'] = $reference;
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function emmr_core_node_presave($node) {

  if ($node->bundle() == "emmr_recipe") {
    // Clear imprecise date fields if date not imprecise.

    if (empty($node->get('field_imprecise_date')->getValue()[0]['value'])) {
      $node->get('field_recipe_date_text')->setValue("");
      $node->get('field_recipe_date_to')->setValue("");
    }

    if (!empty($node->get('field_annotations')->getValue())) {
      $annos = $node->get('field_annotations')->getValue();

      foreach ($annos as $key => $anno) {

        if (!empty($annos[$key]['subform'])) {
          if (empty($annos[$key]['subform']['field_annotation_text'][0]['value'])) {
            unset($annos[$key]);
          }
        }
      }

      $node->get('field_annotations')->setValue($annos);
    }

    if (!empty($node->get('field_contributors')->getValue())) {
      $contribs = $node->get('field_contributors')->getValue();

      foreach ($contribs as $key => $contrib) {

        if (!empty($contribs[$key]['subform'])) {
          if (empty($contribs[$key]['subform']['field_contributor_name'][0]['value'])) {
            unset($contribs[$key]);
          }
        }
      }
      $node->get('field_contributors')->setValue($contribs);
    }

    // Update text search ingredients list.
    $ing_list = $node->get('field_ingredients')->getValue();
    $ingredients = "";

    foreach ($ing_list as $ing) {
      $ingredients .= $ing['value'] . " ";
    }

    $node->get('field_ingredients_index')->setValue($ingredients);

    // Update text search symptoms list.
    $sym_list = $node->get('field_symptoms')->getValue();
    $symptoms = "";

    foreach ($sym_list as $sym) {
      $symptoms .= $sym['value'] . " ";
    }

    $node->get('field_symptoms_index')->setValue($symptoms);

    // Re-number transcription marginalia.
    $trans = $node->field_recipe_transcription->getValue()[0]['value'];
    // Find marginalia item matches.
    preg_match_all('/<trxnmar>(.*?)<\/trxnmar>/', $trans, $matches);
    // Iterate.
    foreach ($matches as $key => $marginalia) {
      // Get full expression match
      $original = $marginalia[0] ?? NULL;
      if ($original) {
        // Get number segment.
        preg_match_all('/<span class="trxn-number">(.*?)<\/span>/', $original, $number);
        // Build sequential number segment.
        $i = $key + 1;
        $new = "<span class='trxn-number'>$i</span>";
        // Replace original number segment in original match.
        $replacement = str_replace($number[0], $new, $original, $count);
        // Replace marginalia segment in transcription.
        $trans = str_replace($marginalia, $replacement, $trans, $count);
        // Update field and save.
        $node->field_recipe_transcription->setValue([
          'value' => $trans,
          'format' => 'unb_libraries',
        ]);
      }    
    }
  }
}

/**
 * Implements hook_FORM_ID_alter().
 */
function emmr_core_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "node_emmr_recipe_form" ||
  $form_id == "node_emmr_recipe_edit_form") {

    $form['#validate'][] = 'validate_date_text';

    $form['field_recipe_date_to']['#states']['invisible'][':input[name="field_imprecise_date[value]"]']
      = ['checked' => FALSE];
    $form['field_recipe_date_text']['#states']['invisible'][':input[name="field_imprecise_date[value]"]']
      = ['checked' => FALSE];
  }

  // Add exact-match checkbox for keyword search.
  if ($form_id == "views_exposed_form") {
    $view = $form_state->getStorage('view');

    if ($view['view']->id() == 'emmr_browse_recipes' and $view['view']->current_display == 'page_1') {

      $form['exact_keyword'] = [
        '#type' => 'checkbox',
        '#title' => t('Exact match'),
        '#required' => FALSE,
        '#default_value' => FALSE,
        '#weight' => 0,
      ];
    }

    array_unshift($form['#submit'], 'search_exact_match');
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 * Attach annotation safety constraint.
 */
function emmr_core_entity_bundle_field_info_alter(&$fields, $entity_type, $bundle) {
  // Target only annotation paragraphs.
  if ($entity_type->id() === 'paragraph' && $bundle === 'emmr_annotation') {

    if (isset($fields['field_annotation_text'])) {
    // Add our custom validation to the annotation text field.
    $fields['field_annotation_text']->addConstraint('AnnoSafe');
    }

    if (isset($fields['field_alt_spellings'])) {
    // Add our custom validation to the annotation text field.
    $fields['field_alt_spellings']->addConstraint('AnnoSafe');
    }
  }

}

/**
 * Callback validation function for recipe-edit.
 */
function validate_date_text(&$form, $form_state) {
  $imp_date = $form_state->getValue('field_imprecise_date')['value'];
  $date_txt = $form_state->getValue('field_recipe_date_text')[0]['value'];

  if ($imp_date && $date_txt == "") {
    $form_state->setErrorByName('field_recipe_date_text',
      t('Imprecise dates must contain a date description.'));
  }
}

/**
 * Callback exact-match function for keyword search.
 */
function search_exact_match(&$form, $form_state) {
  $keyword = $form_state->getValue('combine');
  $title = $form_state->getValue('title');
  $contributor = $form_state->getValue('field_contributor_name_value');
  $exact = $form_state->getValue('exact_keyword');

  if ($exact) {
    if (!empty($keyword) and !in_array($keyword[0], ['"', "'"])) {
      $form_state->setValue('combine', '" ' . $keyword . ' "');
    }
  }

}

/**
 * Implements hook_views_query_alter().
 */
function emmr_core_views_query_alter($view, $query) {
  $view = $query->view;
  $view_id = $view->id();
  $view_disp = $view->current_display;

  if ($view_id == "emmr_browse_recipes" && $view_disp == "page_1") {
    $date_where = $query->where['2']['conditions'];
    $date_min = date('c',
      strtotime($query->view->exposed_data['field_recipe_date_value']['min']));

    if (count($date_where)) {
      $where2 = str_replace('date', 'date_to',
        $date_where[0]);
      $query->where['2']['conditions'][] = $where2;

      $where3 = $date_where[0];
      $where3['field'] =
        "DATE_FORMAT('" . $date_min . "', '%Y-%m-%d')
        BETWEEN
        DATE_FORMAT(node__field_recipe_date.field_recipe_date_value, '%Y-%m-%d')
        AND DATE_FORMAT(node__field_recipe_date_to.field_recipe_date_to_value, '%Y-%m-%d')";

      $query->where['2']['conditions'][] = $where3;
    }
  }
}
