language: php
sudo: required

services:
  - docker

php:
  - '7.1'

cache:
  directories:
        - $HOME/.composer/cache

env:
  global:
    - SERVICE_NAME=emmr.lib.unb.ca
    - AMAZON_ECR_REGION=us-east-1
    - DEPLOY_BRANCHES=dev,prod
    - DEPLOYMENT_FINISHED_MARKER=99_report_as_complete
    - DOCKER_UPSTREAM_IMAGE=unblibraries/drupal:alpine-nginx-php7-8.x-composer
    - OLD_IMAGES_TO_KEEP=2
    - SERVICE_DEPLOY_PORT=80
    - SERVICE_TEST_UP_PATH=/user

before_install:
  - git clone git://github.com/unb-libraries/CargoDock.git CargoDock
  - CargoDock/travis/installDockerCompose.sh

before_script:
  - CargoDock/travis/setComposePort.sh
  - CargoDock/travis/setDockerComposeEnv.sh
  - CargoDock/travis/buildInstanceForTesting.sh
  - CargoDock/travis/waitForDeploy.sh
  - CargoDock/travis/checkStartupForErrors.sh

script:
  - CargoDock/travis/testInstance.sh

after_success:
  - CargoDock/aws/installAuthAws.sh
  - CargoDock/travis/buildInstanceTheme.sh
  - CargoDock/travis/buildImagePushToRepo.sh
  - CargoDock/travis/cleanupOldImages.sh
  - CargoDock/travis/triggerKubeDeploy.sh

notifications:
  slack:
    rooms:
      secure: qwsELAVYCAJSAgOmnGzoIfpoxqiQwZ0nzN6lmjRAR4JAHxuLSvrjwjRiEQK8KwFBscUv+2Bcd6mNpp6ngGEX0+nABi7DNRtexzR+zJ3I1sADhPqHERobgk5HB4au51WZwlMZlzlEvMIUwqVHCKz3dBQyaJkyHEdtmyPOUj801BhlzXCvqyaqwvSuFIyKhLm/o2MZoU1hcGe1ID5xnMkzzQzM9szvmmkmsB8BVwiU/h/p+5Ex/6qBU3Clnja5UR4PQGa72VPue2SquNCQhKQlAk8/LUtTmz7vicdIQpgOma0TqXkBOuxrqOcBa1fNHd4fCxhfWO6HuGUGZiIJ+gLSafetC5CfUtZjlnxoZ0jxxxLFLswHXVyVfkzioL5rHw8TjXbsrFEv/hLN5cgmjQ1zOBhRLAUSkKZt+AsLVJUFW58eho8fKfFAeHa4FvtYT2ZmEsBLUt917hqvN0gMpZRIvU3mptIgRBcDJLCC1Mt+nPwxnv9QX9oUnBW0Snx/hbZ/sfTNIep+PDRp2c1x1OjRov+7JWYyxvy6b4ebCp69m7B2ZSpXoJHenHCqsvUG4dZ0Fouzb4J9QAwJKX1at3VfqxRdi0UqFhYYJJgFLW4QhU2CZpefER5iK+ZtcxE2IzcPsjczPT1QDx4WC7xq3ZV9vyy3x/5t9ehN2rP8Jp/+MYA=
    on_start: always
    on_success: always
