language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: G8L5fk4S7nPgurX1pdwQqJbGxi1lKHq/jPlyTMYdNO5fRgknTP7bjNZZD6qCX2uU01LorTnv+jW7WGGCFIfE3VFhU3VWGwANsI6japKe+zX3oVt4k7vGdHmtKW2iZlPhXHEodfTbc4+AGremR6+cFmeLKpBOK5YaVr2yujoJvr8QFQNBUx20J99jM9HyFKLEfRGgWpoyTDMNbXHLCp7qCHpupPA6P6ZQst51dvw6JRAl08MVzBzAvYxNBZzpg4AC5sz/Jc77lM57U38uo3Ru8B4OF+czWV83e2w1oqwax8v8gQTqHdU8VvXYn0K2iV2vk6Q0ihjeKKtuRQFZEmIkkGrnvGyLIk6YcUYr9jUPMo8sk5L3A4p6TPnFrqruWLzspLLvG+UcCMb539mlpnKzNuhI7FWZc5H9zIdy++GgXkX1oyK5yazy/S7q30i1ayPgoSbq2MmIIXmZErBq4MemijDQSyo7MEl/8yeOvkYRD86pvhLA3NG3Q7HrrX7jVdc/7DEcnXlHPPSvzLnOL42hlxPQetkuNZsPI32RzBuzsqOCLM3w4KHdQZB9laM95KlIG4Lp2a7II/4idcfg4MKnoPztXPSj79uFgdvtDgv0HuN7X42Nb4k8sK+GygWOtzgQR4lQv25TqN0sYwPdnvvs4l5AH827pmfg87fsrFderac=
    on_start: always
    on_success: always
