<?php

/**
 * @file
 * Contains emmr_pdf.module.
 */

 // Reference the Dompdf namespace.
use Dompdf\Dompdf;

/**
 * Implements hook_preprocess_hook().
 */
function emmr_pdf_views_pre_view($view, $display_id, &$args) {

  if ($view->id() == 'emmr_adv_sources') {
    // Instantiate and use the dompdf class.
    $dompdf = new Dompdf();
    $dompdf->loadHtml('hello world');

    // (Optional) Setup the paper size and orientation.
    $dompdf->setPaper('A4', 'landscape');

    // Render the HTML as PDF.
    $dompdf->render();

    // Output the generated PDF to Browser.
    $dompdf->stream();

    drupal_set_message("Done!");
  }
}
