<?php

/**
 * @file
 * Contains emmr_pdf.module.
 */

 // Reference the Dompdf namespace.
use Dompdf\Dompdf;

/**
 * Implements hook_preprocess_hook().
 */
function emmr_pdf_views_pre_view($view, $display_id, &$args) {

  if ($view->id() == 'emmr_adv_sources') {
    // Instantiate and use the dompdf class.
    $dompdf = new Dompdf();

    // Render node view html to string.
    $node = \Drupal::entityManager()->getStorage('node')->load(2);
    $view_builder = \Drupal::entityManager()->getViewBuilder('node');
    $renderarray = $view_builder->view($node, 'full');
    $html = \Drupal::service('renderer')->renderRoot($renderarray);

    // Load html into dompdf.
    $dompdf->loadHtml($html);

    // Render the HTML as PDF.
    $dompdf->render();

    // Output the generated PDF to Browser.
    $dompdf->stream();
    kint($html);

    drupal_set_message("Done!");
  }
}
