<?php

/**
 * @file
 * Contains emmr_pdf.module.
 */

 // reference the Dompdf namespace
use Dompdf\Dompdf;

/**
 * Implements hook_preprocess_hook().
 */
function emmr_pdf_preprocess_emmr_intro(&$variables) {
  // instantiate and use the dompdf class
  $dompdf = new Dompdf();
  $dompdf->loadHtml('hello world');

  // (Optional) Setup the paper size and orientation
  $dompdf->setPaper('A4', 'landscape');

  // Render the HTML as PDF
  $dompdf->render();

  // Output the generated PDF to Browser
  $dompdf->stream();

  drupal_set_message("Done!");
}
