<?php

/**
 * @file
 * Contains emmr_search.module.
 */

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function emmr_search_node_presave($entity) {
  // Generate plain contributor(s) on entity save.
  $type = $entity->getType();
  $fields = $entity->getFields();
  $contribs = $fields['field_contributors']->getValue();
  $p_contribs = '';

  if ($type = 'emmr_recipe') {

    foreach ($contribs as $contributor) {
      $cont_name =
        $contributor['subform']['field_contributor_name'][0]['value'];
      $p_contribs = $p_contribs . $cont_name . ' ';
      $fields['field_plain_contributors']->setValue($p_contribs);
    }
  }
}
