schemas:
  bootstrap: 8000
  emmr_lib_unb_ca: 8000
favicon:
  mimetype: image/png
  path: themes/custom/emmr_lib_unb_ca/images/favicon.png
  url: 'http://localhost:3093/themes/custom/emmr_lib_unb_ca/images/favicon.png'
  use_default: 0
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
  node_user_picture: 0
logo:
  path: ''
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
button_colorize: 0
button_iconize: 0
